version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  producer:
    build: ./producer
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
      - processor
    volumes:
      - ./data/cub_200_2011:/app/cub_200_2011
    networks:
      - app-network

  processor:
    build: ./processor
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
      - uploader
    networks:
      - app-network

  uploader:
    build: ./uploader
    environment:
      RABBITMQ_HOST: rabbitmq
      MONGO_HOST: mongodb
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - app-network

  presenter:
    build: ./presenter
    environment:
      RABBITMQ_HOST: rabbitmq
      MONGO_HOST: mongodb
    depends_on:
      - rabbitmq
      - mongodb
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
