version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - ./data/cub_200_2011:/app/cub_200_2011
    networks:
      - app-network

  processor:
    build:
      context: ./processor
      dockerfile: Dockerfile
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - app-network

  uploader:
    build:
      context: ./uploader
      dockerfile: Dockerfile
    environment:
      RABBITMQ_HOST: rabbitmq
      MONGO_HOST: mongodb
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - app-network

  presenter:
    build:
      context: ./presenter
      dockerfile: Dockerfile
    environment:
      RABBITMQ_HOST: rabbitmq
      MONGO_HOST: mongodb
    depends_on:
      - rabbitmq
      - mongodb
    ports:
      - "8000:8000"
    networks:
      - app-network

  trainer:
    build:
      context: ./trainer
      dockerfile: Dockerfile
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - app-network

  predictor:
    build:
      context: ./predictor
      dockerfile: Dockerfile
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
